### ISSUE TITLE
web端更新后的一个错误&脚本优化

### ISSUE THREAD

**Issue by leisiyu1** [yige233/bettermew#1]
网页更新后，点击个人主页会强制跳转出搜索界面
其他建议：
采用其他方式弹出@提醒
将关闭图片改为可选
点击头像时@xxx;删除分号，改为空格

**Comment by leisiyu1** [comment]
确定了一个问题
如果想法中存在脚本内容会干扰执行（什么莫名其妙的bug.jpg）

**Comment by yige233** [comment]
关于第一个问题，我这里复现失败，请提供下脚本的版本号和问题截图（或者录屏），脚本最新是0.55。
其他建议会考虑的，我自己对@功能也不太满意





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yige233/bettermew"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月17日(星期二) 晚上7:36
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[yige233/bettermew] web端更新后的一个错误&amp;脚本优化 (#1)





 
网页更新后，点击个人主页会强制跳转出搜索界面
 其他建议：
 采用其他方式弹出@提醒
 将关闭图片改为可选
 ***@***.***;删除分号，改为空格
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yige233** [comment]
略迷…………
能否发一下版本号，以及出现问题时的截屏或录屏呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yige233/bettermew"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月17日(星期二) 晚上9:58
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [yige233/bettermew] web端更新后的一个错误&amp;脚本优化 (#1)





 
确定了一个问题
 如果想法中存在脚本内容会干扰执行（什么莫名其妙的bug.jpg）
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by leisiyu1** [comment]
第一个发现了，
把全部code复制到想法，发布后点自己主页就会炸
@功能一个改进已经发到站内想法上，
（直接mew私信也许会好些？）

**Comment by yige233** [comment]
有关掉脚本确认是脚本问题吗？不过我还是不清楚具体触发过程，希望能有个录屏（摄屏也行），最好包含控制台



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月18日(星期三) 晚上6:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yige233/bettermew] web端更新后的一个错误&amp;脚本优化 (#1)





 
第一个发现了，
 把全部code复制到想法，发布后点自己主页就会炸
 @功能一个改进已经发到站内想法上，
 （直接mew私信也许会好些？）
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by leisiyu1** [comment]
![image](https://user-images.githubusercontent.com/53390868/129895058-f18c9e93-4943-4ec2-826d-8f477cfe9f72.png)
就是将js发布到自己的想法中，
把code全部粘贴到正文，不需要打开文章就会触发

**Comment by leisiyu1** [comment]
只有个人主页会触发（莫名其妙）

**Comment by leisiyu1** [comment]
对了，要不mew站内私信吧，也方便些QAQ
